'use client'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Plus } from 'lucide-react'
import { supabase } from '@/lib/supabase'
type Buyer={id:string;full_name:string;last_checked_at:string|null;buyer_searches?:any[]}
type Match={id:string;score:number;created_at:string;buyers:{full_name:string}|null;offers:{title:string|null;district:string|null;price_eur:number|null}|null}
export default function Dashboard(){const router=useRouter();const[buyers,setBuyers]=useState<Buyer[]>([]);const[matches,setMatches]=useState<Match[]>([]);const[loading,setLoading]=useState(true)
useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const[{data:b},{data:m}]=await Promise.all([supabase.from('buyers').select('id,full_name,last_checked_at,buyer_searches(id)').eq('is_active',true).order('created_at',{ascending:false}),supabase.from('offer_matches').select('id,score,created_at,buyers(full_name),offers(title,district,price_eur)').eq('status','new').order('score',{ascending:false}).limit(5)]);setBuyers((b||[]) as any);setMatches((m||[]) as any);setLoading(false)})()},[router])
return <><div className="topline"><div><div className="eyebrow">Buyer intelligence</div><h1>Начало</h1><div className="subtitle">Какво ново има за твоите клиенти?</div></div><Link className="btn primary" href="/buyers"><Plus size={17}/>Нов купувач</Link></div><section className="grid4"><div className="stat"><span className="label">Активни купувачи</span><strong>{loading?'—':buyers.length}</strong><span className="delta">с активно търсене</span></div><div className="stat"><span className="label">Нови съвпадения</span><strong>{loading?'—':matches.length}</strong><span className="delta">чакат преглед</span></div><div className="stat"><span className="label">Над 90%</span><strong>{loading?'—':matches.filter(m=>m.score>=90).length}</strong><span className="delta">за незабавна реакция</span></div><div className="stat"><span className="label">Оперативка</span><strong>10</strong><span className="delta">целеви предложения</span></div></section><section className="split"><div className="card"><h2>Последни съвпадения</h2>{matches.length?matches.map(m=><div className="matchRow" key={m.id}><div className="score">{m.score}%</div><div className="grow"><b>{m.buyers?.full_name||'Клиент'} ↔ {m.offers?.title||'Нова оферта'}</b><div className="meta">{m.offers?.district||'—'} · {m.offers?.price_eur?`€${Number(m.offers.price_eur).toLocaleString('bg-BG')}`:'Цена не е посочена'}</div></div><span className="tag">Ново</span></div>):<div className="empty">Още няма съвпадения. Когато външният мониторинг открие оферти, те ще се появяват тук.</div>}</div><div className="card"><h2>Моите купувачи</h2>{buyers.length?buyers.slice(0,6).map(b=><div className="buyerRow" key={b.id}><span className="statusDot"/><div className="grow"><b>{b.full_name}</b><div className="meta">{b.buyer_searches?.length||0} активно търсене</div></div></div>):<div className="empty">Добави първия купувач и критериите му.</div>}</div></section></>}
